### ISSUE TITLE
New Build

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#34]
Do we need a new build? Should it pick Mame 2.66?

**Comment by sam-ludlow** [comment]
Hello Paul

MAME-AO will only use the MAME version that the archive.org item https://archive.org/details/mame-merged is on (parsed from the title).

Since I started this project I've only ever seen it a few days after the MAME release, hopefully the guy is on holiday or something?

I'm starting to think add an option that allows you to MAME version bump. Although the ROMS wouldn't be available but you could manually import them from the Pleasuredome Torrent Update.

Cheers
Sam

**Comment by paulmortlock** [comment]
Aha can we get a new build 1.88

**Comment by sam-ludlow** [comment]
Coming soon

1.88 will have asset placing reports option - shows exactly what its doing with ROMs & DISKs. 
1.89 will maybe have a MAME version bump function - but you will be on your own importing the ROMs.

**Comment by paulmortlock** [comment]
Excellent Sam

**Comment by sam-ludlow** [comment]
Hello @paulmortlock 

I have implemented a setting to track latest MAME on GitHub rather that Archive.org in 1.89.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/612b494a-a9fe-4d0d-b5c0-1b4569b52fad)

It looks like Archive.Org machine ROMs where up to date anyway, I think the maintainer just forgot to version bump the title.

Running the "source exists machine rom" shows nothing missing.

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/55a7696a-84ec-4162-bd95-2b4e454f69f4)

I was able to play a new machine from whatsnew.txt no problem "Jumbo Godzilla".

So this option was defiantly required.

Cheers
Sam

**Comment by paulmortlock** [comment]
Excellent Sam. Can you include an installer along with the zip file, like a MSI or equivalent this may enable it run on Linux with Wine as it could install the dependencies.

**Comment by sam-ludlow** [comment]
Closing the version thing seems to work.

Paul you can open a new issue for the installer if you like, been thinking about it.

**Comment by paulmortlock** [comment]
Sure
