### ISSUE TITLE
crossplatform #2/

### ISSUE THREAD

**Issue by cewatkins** [sam-ludlow/mame-ao#43]
Loading XML Z:\home\oo\Downloads\mameao192\0267\_software.xml ...
!!! FATAL ERROR: There is an unclosed literal string. Line 845910, position 26.

i think, the wine things totally broke, i haven't been able to look at it locally,
but with the http error, i think these are cross platform...

**Comment by cewatkins** [comment]
so, i delete file it makes, it, but because of similar issue. gets further.
this seems to be a thing as well, maybe in the .doc to waste the _*.xml files, etc.

**Comment by sam-ludlow** [comment]
Hello @cewatkins 

This normally happens when RAM gets low, MAME-AO spawns MAME to dump out the XML then MAME bombs out half way through outputting the XML. Then everything crashes.

Then next time MAME-AO starts it thinks the XML has already been dumped, then goes to parse it but the XML is incomplete..

Yes kill the _*.xml  and try again with plenty of RAM available.

Thanks for reminding me, this could do with fixing so the XML goes to temp file first and then gets moved if it works, rather than leaving a broken XML file.

Cheers
Sam

**Comment by sam-ludlow** [comment]
Fixed in 1.93

When dumping XML from MAME use a temp file and only move when it completes.

Had a few reports of this - it seems when RAM is low this step is most likely to fail.
